#! /bin/bash

source activate tfm

git clone git@github.com:cabadsanchez/relation_classification.git

cd relation_classification

mkdir dumps

gsutil cp gs://storage-tfm/data_LSTM-SDP.pkl.gz dumps/

cd SDP-LSTM

python SDP-LSTM.py >> ../dumps/SDP-LSTM.log

gsutil -m cp -r ../dumps gs://storage-tfm/

sudo shutdown -h now